/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'faq': RouteRecordInfo<'faq', '/faq', Record<never, never>, Record<never, never>>,
    'features': RouteRecordInfo<'features', '/features', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'oauth2-redirect': RouteRecordInfo<'oauth2-redirect', '/oauth2-redirect', Record<never, never>, Record<never, never>>,
    'pricing': RouteRecordInfo<'pricing', '/pricing', Record<never, never>, Record<never, never>>,
    'privacy': RouteRecordInfo<'privacy', '/privacy', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'reset-password': RouteRecordInfo<'reset-password', '/reset-password', Record<never, never>, Record<never, never>>,
    'shop-admin-business-settings': RouteRecordInfo<'shop-admin-business-settings', '/shop-admin/business-settings', Record<never, never>, Record<never, never>>,
    'shop-admin-business-settings-holidays': RouteRecordInfo<'shop-admin-business-settings-holidays', '/shop-admin/business-settings/holidays', Record<never, never>, Record<never, never>>,
    'shop-admin-business-settings-hours': RouteRecordInfo<'shop-admin-business-settings-hours', '/shop-admin/business-settings/hours', Record<never, never>, Record<never, never>>,
    'shop-admin-coupon': RouteRecordInfo<'shop-admin-coupon', '/shop-admin/coupon', Record<never, never>, Record<never, never>>,
    'shop-admin-customers-components-customer-detail-dialog': RouteRecordInfo<'shop-admin-customers-components-customer-detail-dialog', '/shop-admin/customers/components/CustomerDetailDialog', Record<never, never>, Record<never, never>>,
    'shop-admin-customers-components-customer-dialog': RouteRecordInfo<'shop-admin-customers-components-customer-dialog', '/shop-admin/customers/components/CustomerDialog', Record<never, never>, Record<never, never>>,
    'shop-admin-customers-components-customer-form-dialog': RouteRecordInfo<'shop-admin-customers-components-customer-form-dialog', '/shop-admin/customers/components/CustomerFormDialog', Record<never, never>, Record<never, never>>,
    'shop-admin-customers-list': RouteRecordInfo<'shop-admin-customers-list', '/shop-admin/customers/list', Record<never, never>, Record<never, never>>,
    'shop-admin-dashboard': RouteRecordInfo<'shop-admin-dashboard', '/shop-admin/dashboard', Record<never, never>, Record<never, never>>,
    'shop-admin-payment': RouteRecordInfo<'shop-admin-payment', '/shop-admin/payment', Record<never, never>, Record<never, never>>,
    'shop-admin-payment-history': RouteRecordInfo<'shop-admin-payment-history', '/shop-admin/payment/history', Record<never, never>, Record<never, never>>,
    'shop-admin-reservations-calendar': RouteRecordInfo<'shop-admin-reservations-calendar', '/shop-admin/reservations/calendar', Record<never, never>, Record<never, never>>,
    'shop-admin-reservations-components-assign-staff-dialog': RouteRecordInfo<'shop-admin-reservations-components-assign-staff-dialog', '/shop-admin/reservations/components/AssignStaffDialog', Record<never, never>, Record<never, never>>,
    'shop-admin-reservations-components-reservation-detail-dialog': RouteRecordInfo<'shop-admin-reservations-components-reservation-detail-dialog', '/shop-admin/reservations/components/ReservationDetailDialog', Record<never, never>, Record<never, never>>,
    'shop-admin-reservations-components-reservation-dialog': RouteRecordInfo<'shop-admin-reservations-components-reservation-dialog', '/shop-admin/reservations/components/ReservationDialog', Record<never, never>, Record<never, never>>,
    'shop-admin-reservations-components-reservation-form-dialog': RouteRecordInfo<'shop-admin-reservations-components-reservation-form-dialog', '/shop-admin/reservations/components/ReservationFormDialog', Record<never, never>, Record<never, never>>,
    'shop-admin-reservations-list': RouteRecordInfo<'shop-admin-reservations-list', '/shop-admin/reservations/list', Record<never, never>, Record<never, never>>,
    'shop-admin-services-components-category-manage-dialog': RouteRecordInfo<'shop-admin-services-components-category-manage-dialog', '/shop-admin/services/components/CategoryManageDialog', Record<never, never>, Record<never, never>>,
    'shop-admin-services-components-service-detail-dialog': RouteRecordInfo<'shop-admin-services-components-service-detail-dialog', '/shop-admin/services/components/ServiceDetailDialog', Record<never, never>, Record<never, never>>,
    'shop-admin-services-components-service-dialog': RouteRecordInfo<'shop-admin-services-components-service-dialog', '/shop-admin/services/components/ServiceDialog', Record<never, never>, Record<never, never>>,
    'shop-admin-services-components-service-form-dialog': RouteRecordInfo<'shop-admin-services-components-service-form-dialog', '/shop-admin/services/components/ServiceFormDialog', Record<never, never>, Record<never, never>>,
    'shop-admin-services-list': RouteRecordInfo<'shop-admin-services-list', '/shop-admin/services/list', Record<never, never>, Record<never, never>>,
    'shop-admin-staffs-components-staff-detail-dialog': RouteRecordInfo<'shop-admin-staffs-components-staff-detail-dialog', '/shop-admin/staffs/components/StaffDetailDialog', Record<never, never>, Record<never, never>>,
    'shop-admin-staffs-components-staff-dialog': RouteRecordInfo<'shop-admin-staffs-components-staff-dialog', '/shop-admin/staffs/components/StaffDialog', Record<never, never>, Record<never, never>>,
    'shop-admin-staffs-components-staff-form-dialog': RouteRecordInfo<'shop-admin-staffs-components-staff-form-dialog', '/shop-admin/staffs/components/StaffFormDialog', Record<never, never>, Record<never, never>>,
    'shop-admin-staffs-list': RouteRecordInfo<'shop-admin-staffs-list', '/shop-admin/staffs/list', Record<never, never>, Record<never, never>>,
    'shop-admin-subscription': RouteRecordInfo<'shop-admin-subscription', '/shop-admin/subscription', Record<never, never>, Record<never, never>>,
    'shop-admin-super-audit-logs': RouteRecordInfo<'shop-admin-super-audit-logs', '/shop-admin/super/audit-logs', Record<never, never>, Record<never, never>>,
    'shop-admin-super-businesses': RouteRecordInfo<'shop-admin-super-businesses', '/shop-admin/super/businesses', Record<never, never>, Record<never, never>>,
    'shop-admin-super-dashboard': RouteRecordInfo<'shop-admin-super-dashboard', '/shop-admin/super/dashboard', Record<never, never>, Record<never, never>>,
    'shop-admin-super-users': RouteRecordInfo<'shop-admin-super-users', '/shop-admin/super/users', Record<never, never>, Record<never, never>>,
    'support': RouteRecordInfo<'support', '/support', Record<never, never>, Record<never, never>>,
    'terms': RouteRecordInfo<'terms', '/terms', Record<never, never>, Record<never, never>>,
  }
}
