/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'business-settings': RouteRecordInfo<'business-settings', '/business-settings', Record<never, never>, Record<never, never>>,
    'business-settings-holidays': RouteRecordInfo<'business-settings-holidays', '/business-settings/holidays', Record<never, never>, Record<never, never>>,
    'business-settings-hours': RouteRecordInfo<'business-settings-hours', '/business-settings/hours', Record<never, never>, Record<never, never>>,
    'customers-components-customer-detail-dialog': RouteRecordInfo<'customers-components-customer-detail-dialog', '/customers/components/CustomerDetailDialog', Record<never, never>, Record<never, never>>,
    'customers-components-customer-dialog': RouteRecordInfo<'customers-components-customer-dialog', '/customers/components/CustomerDialog', Record<never, never>, Record<never, never>>,
    'customers-components-customer-form-dialog': RouteRecordInfo<'customers-components-customer-form-dialog', '/customers/components/CustomerFormDialog', Record<never, never>, Record<never, never>>,
    'customers-list': RouteRecordInfo<'customers-list', '/customers/list', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'reservations-calendar': RouteRecordInfo<'reservations-calendar', '/reservations/calendar', Record<never, never>, Record<never, never>>,
    'reservations-components-assign-staff-dialog': RouteRecordInfo<'reservations-components-assign-staff-dialog', '/reservations/components/AssignStaffDialog', Record<never, never>, Record<never, never>>,
    'reservations-components-reservation-detail-dialog': RouteRecordInfo<'reservations-components-reservation-detail-dialog', '/reservations/components/ReservationDetailDialog', Record<never, never>, Record<never, never>>,
    'reservations-components-reservation-dialog': RouteRecordInfo<'reservations-components-reservation-dialog', '/reservations/components/ReservationDialog', Record<never, never>, Record<never, never>>,
    'reservations-components-reservation-form-dialog': RouteRecordInfo<'reservations-components-reservation-form-dialog', '/reservations/components/ReservationFormDialog', Record<never, never>, Record<never, never>>,
    'reservations-list': RouteRecordInfo<'reservations-list', '/reservations/list', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'services-components-service-detail-dialog': RouteRecordInfo<'services-components-service-detail-dialog', '/services/components/ServiceDetailDialog', Record<never, never>, Record<never, never>>,
    'services-components-service-dialog': RouteRecordInfo<'services-components-service-dialog', '/services/components/ServiceDialog', Record<never, never>, Record<never, never>>,
    'services-components-service-form-dialog': RouteRecordInfo<'services-components-service-form-dialog', '/services/components/ServiceFormDialog', Record<never, never>, Record<never, never>>,
    'services-list': RouteRecordInfo<'services-list', '/services/list', Record<never, never>, Record<never, never>>,
    'staffs-components-staff-detail-dialog': RouteRecordInfo<'staffs-components-staff-detail-dialog', '/staffs/components/StaffDetailDialog', Record<never, never>, Record<never, never>>,
    'staffs-components-staff-dialog': RouteRecordInfo<'staffs-components-staff-dialog', '/staffs/components/StaffDialog', Record<never, never>, Record<never, never>>,
    'staffs-components-staff-form-dialog': RouteRecordInfo<'staffs-components-staff-form-dialog', '/staffs/components/StaffFormDialog', Record<never, never>, Record<never, never>>,
    'staffs-list': RouteRecordInfo<'staffs-list', '/staffs/list', Record<never, never>, Record<never, never>>,
  }
}
